version: '3'

services:
  app:
    container_name: Blog-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/blog
    environment:
      - APP_ENV=production
    command: go run main.go
